version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx-dx
    ports:
      - 32132:80
    # docker exec nginx-dx nginx -s reload
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - newara-network

networks:
  newara-network:
    name: newara-network
