version: '3'

services:
  newara-web:
    image: newara-dx/web
    restart: always
    networks:
     - newara-network
    volumes:
      - ./web/.env:/tmp/env/.env
      - newara-web:/usr/src/app
      - newara-ssh:/root/.ssh
       
  newara-api:
    image: newara-dx/api
    restart: always
    ports:
      - 22
    depends_on:
      - newara-redis
      - newara-elasticsearch
    volumes:
      - ./volumes/root:/root
      - ./volumes/log:/var/log/newara
      - ./volumes/elastic-api:/newara/www/ara/db/elasticsearch
      - ./api/firebaseServiceAccountKey.json:/tmp/env/firebaseServiceAccountKey.json
      - ./api/.env:/tmp/env/.env
      - newara-web:/root/web
      - newara-ssh:/root/.ssh
    networks:
      - newara-network

  newara-db:
    image: mysql:5.7
    ports:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=supereasypassw0rd
      - MYSQL_DATABASE=new_ara
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    volumes:
      - ./volumes/db:/var/lib/mysql
    networks:
      - newara-network

  newara-redis:
    image: redis:6
    networks:
      - newara-network

  newara-elasticsearch:
    image: elasticsearch:7.9.2
    environment:
      - discovery.type=single-node
    volumes:
      - ./volumes/root/api/ara/db/elasticsearch/synonym.txt:/usr/share/elasticsearch/config/analysis/synonym.txt
      - newara-esdata:/usr/share/elasticsearch/data
    networks:
      - newara-network
        

volumes:
  newara-esdata:
  newara-web:
  newara-ssh:

networks:
  newara-network:
    name: newara-network
    external: true
    
