version: '3'

services:
  web:
    image: newara-dx/web
    restart: always
    networks:
     - newara-network
    volumes:
      - ./web/.env:/tmp/env/.env
      - web-volume:/usr/src/app
      - ssh-volume:/root/.ssh
       
  api:
    image: newara-dx/api
    restart: always
    ports:
      - 22
    depends_on:
      - redis
      - elasticsearch
    volumes:
      - ./volumes/root:/root
      - ./volumes/log:/var/log/newara
      - ./volumes/elastic-api:/newara/www/ara/db/elasticsearch
      - ./api/firebaseServiceAccountKey.json:/tmp/env/firebaseServiceAccountKey.json
      - ./api/.env:/tmp/env/.env
      - web-volume:/root/web
      - ssh-volume:/root/.ssh
    networks:
      - newara-network

  db:
    image: mysql:5.7
    ports:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=supereasypassw0rd
      - MYSQL_DATABASE=new_ara
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    volumes:
      - ./volumes/db:/var/lib/mysql
    networks:
      - newara-network

  redis:
    image: redis:6
    networks:
      - newara-network

  elasticsearch:
    image: elasticsearch:7.9.2
    environment:
      - discovery.type=single-node
    volumes:
      - ./volumes/root/api/ara/db/elasticsearch/synonym.txt:/usr/share/elasticsearch/config/analysis/synonym.txt
      - esdata:/usr/share/elasticsearch/data
    networks:
      - newara-network
        

volumes:
  esdata:
  web-volume:
  ssh-volume:

networks:
  newara-network:
    name: newara-network
    external: true
    
